name: What time is it?
on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"

env:
  MIRROR: "Hello"
  EXECUTABLE: "World"

jobs:
  what_time_is_it:
    runs-on: ubuntu-latest
    steps:
    - name: "What's the time?"
      run: "date +%T"

