name: Choco

on:
  push:
    branches-ignore:
    - "ga-ignore-*"
  pull_request:
    branches-ignore:
    - "ga-ignore-*"
  schedule:
  - cron: '0 0 * * *'

env:
  SOURCE: Hanra-s-work/improved-bassoon-chocolatine
  MIRROR: "EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-henry.letellier"
  EXECUTABLE: "hello_world"
  EPITEST_DOCKER: ghcr.io/epitech/coding-style-checker:latest
  GITHUB_SSH_KEY: ${{ secrets.MY_CHOCO_PRIVATE_SSH_KEY }}
  BASH_CHECKER: check_results_v2.sh

jobs:

  repository_mirroring:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Push the content to the mirror repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: git@github.com:${{ env.MIRROR }}.git
        ssh_private_key: ${{ env.GITHUB_SSH_KEY }}

  check_coding_style:
    # runs-on: ${{ EPITEST_DOCKER }}
    runs-on: ubuntu-latest
    needs: repository_mirroring
    if: success()
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: assign execution rights to check.sh
      run: chmod +x ./check.sh
    - name: run check.sh
      run: ./check.sh $(pwd) $(pwd)
    - name: checking the results
      run: chmod +x ./$BASH_CHECKER && ./$BASH_CHECKER
      # run: |
      #   CONTENT="$(cat coding-style-reports.log)"
      #   ILLEGAL_FILES_FOUND=0
      #   for FILE in $CONTENT; do
      #       echo "::error file=$FILE,line=1,endLine=0,title=Unwanted file detected::$FILE"
      #       ILLEGAL_FILES_FOUND=1
      #   done
      #   if [ $ILLEGAL_FILES_FOUND -eq 1 ]; then
      #       exit 1
      #   fi

  job1:
    runs-on: ubuntu-latest
    needs: repository_mirroring
    if: success()
    steps:
    - uses: actions/checkout@v3
    - name: Step 1
      run: echo "Step 1"
    - name: will not fail
      run: ./hello_world

  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: success()
    steps:
    - name: Step 2
      run: echo "Step 2"
